### ISSUE TITLE
warnings

### ISSUE THREAD

**Issue by torosushi** [dimisdas/PHPMailer-AmazonSES-Tutorial#1]
Hello,

Thank you very much for the tutorial and examples.

I have tested and received the email, however I saw error message below:

Warning: simplexml_load_string(): Entity: line 1: parser error : Start tag expected, '<' not found in /home/vipguest/public_html/wp-content/images/class.amazonses.php on line 79

Warning: simplexml_load_string(): HTTP/1.1 200 OK in /home/vipguest/public_html/wp-content/images/class.amazonses.php on line 79

Warning: simplexml_load_string(): ^ in /home/vipguest/public_html/wp-content/images/class.amazonses.php on line 79
AmazonSES Error: HTTP/1.1 200 OK x-amzn-RequestId: 9c45df20-03dd-11e7-a7af-6907f0df61c3 Content-Type: text/xml Content-Length: 338 

How to fix these warnings?

Many thanks.

Jhonson

**Comment by dimisdas** [comment]
Hey Jhonson,

Would you mind me sending me your config, sans the API KEY/pass?

Dimis Daskalakis

**Comment by torosushi** [comment]
`<?php 
require_once ABSPATH .'/wp-content/images/class.amazonses.php';
require_once ABSPATH .'/wp-content/images/class.phpmailer.php';
$mail = new PHPMailer();
$to_ema = 'xx@hotmail.com';
$fr_ema = 'xx@xx.xx.au';
$fr_nm = 'xxx';
$to_id = 4390;
$to_ln = 'x';
$to_tit = 'Mr';
$subj = '[xx.com.au] Rewards earned - Member ID#'.$to_id;

$mail->IsAmazonSES();
$mail->AddAmazonSESKey("x", "x");
$message = file_get_contents('/wp-content/images/phpmailer-1000pt.html');
$message = str_replace('{billing_lastname}', $to_ln, $message); 
$message = str_replace('{user_id}', $to_id, $message); 
$message = str_replace('{title}', $to_tit, $message); 
$message = str_replace('{subject}', $subj, $message); 
$message = str_replace('{email}', $to_ema, $message);
$mail->setFrom($fr_ema , $fr_nm );
$mail->addAddress($to_ema);
$mail->Subject = $subj;
$mail->msgHTML($message);
	if(!$mail->Send()){
	 echo "Mailer Error: " . $mail->ErrorInfo;
	} else {
	 echo "Message sent! "; 
	}
?>`

**Comment by dimisdas** [comment]
Hey torosushi,

I've tested the code extensively. These are just warnings and shouldn't affect functionality (I actually get them too with a similar library by Sendy.co).

You should be able to turn them off by changing [error_reporting](http://php.net/manual/en/function.error-reporting.php).
